num_clients: 12 # the number of local clients
model_name: resnet-18 # only support resnet-18 and CNN
iid: True # True or False, use IID data?
batch_size: 128 # the batch size in the train and test procedure
lr: 0.001 # the lr of each client
comp_strategy: random # only support random,weight and grad
train_epoch: 100 # number of main communication epoch
ep_num: 5 # the number of epoch in every local update procedure
sub_carrier_strategy: restricted-1 # only support no-limit, restricted-1 (1/3 receive all), restricted-2 (1/4 receive all)
cuda: True # use cuda instead of cpu?
amendment_strategy: eq5 # only support eq5 and eq6 which correspond to the eq5 and eq6 in the paper
sigma: 0.01 # the noise of the over-the-air computation
seed: 1 # the random seed
beta: 0.75 # the estimation factor of the E
pow_limit: True # whether the transmit power is limited
pow_allocation_strategy: eq3 # the power allocation strategy when power_limit is True, only support avg and eq3
log_dir: "./logs"
